# Config file for automatic testing at travis-ci.org
dist: xenial
language: python

python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy3.5"

env:
  - NSQ_VERSION=1.0.0-compat GO_VERSION=1.8
  - NSQ_VERSION=1.1.0 GO_VERSION=1.10.3

matrix:
  include:
    - env: TOXENV=docs
    - env: TOXENV=lint

install:
  - sudo apt-get install libsnappy-dev
  - pip install -U tox tox-travis
  - bash ./tests/install-nsq.sh

script: tox
